/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Address } from './models/address';
export type { BooleanApiResponse } from './models/boolean-api-response';
export type { CreateDepartmentDto } from './models/create-department-dto';
export type { CreateLeaveRequestDto } from './models/create-leave-request-dto';
export type { CreatePositionDto } from './models/create-position-dto';
export type { EmployeeDto } from './models/employee-dto';
export { EmployeeType } from './models/employee-type';
export type { LeaveRequestDto } from './models/leave-request-dto';
export type { LeaveRequestDtoApiResponse } from './models/leave-request-dto-api-response';
export type { LeaveRequestDtoIEnumerableApiResponse } from './models/leave-request-dto-i-enumerable-api-response';
export type { SignInRequestDto } from './models/sign-in-request-dto';
export type { UpdateDepartmentDto } from './models/update-department-dto';
export type { UpdateEmployeeDto } from './models/update-employee-dto';
export type { UpdatePositionDto } from './models/update-position-dto';
