/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveRequestDtoIEnumerableApiResponse } from '../../models/leave-request-dto-i-enumerable-api-response';

export interface ApiLeaveEmployeeEmailGet$Plain$Params {
  email: string;
}

export function apiLeaveEmployeeEmailGet$Plain(http: HttpClient, rootUrl: string, params: ApiLeaveEmployeeEmailGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveRequestDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiLeaveEmployeeEmailGet$Plain.PATH, 'get');
  if (params) {
    rb.path('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveRequestDtoIEnumerableApiResponse>;
    })
  );
}

apiLeaveEmployeeEmailGet$Plain.PATH = '/api/leave/employee/{email}';
