/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateLeaveRequestDto } from '../../models/create-leave-request-dto';
import { LeaveRequestDtoApiResponse } from '../../models/leave-request-dto-api-response';

export interface ApiLeavePost$Plain$Params {
      body?: CreateLeaveRequestDto
}

export function apiLeavePost$Plain(http: HttpClient, rootUrl: string, params?: ApiLeavePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveRequestDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiLeavePost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveRequestDtoApiResponse>;
    })
  );
}

apiLeavePost$Plain.PATH = '/api/leave';
