/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Address {
  city?: string | null;
  country?: string | null;
  employeeId?: string;
  id?: string;
  state?: string | null;
  street?: string | null;
  zipCode?: string | null;
}
