/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLeaveRequestDto {
  employeeEmail?: string | null;
  endDate?: string;
  reason?: string | null;
  startDate?: string;
}
