/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { EmployeeType } from '../models/employee-type';
export interface EmployeeDto {
  address?: Address;
  dateOfBirth?: string;
  departmentId?: string;
  departmentName?: string | null;
  email?: string | null;
  employeeType?: EmployeeType;
  firstName?: string | null;
  hireDate?: string;
  id?: string;
  lastName?: string | null;
  positionId?: string;
  positionTitle?: string | null;
  userName?: string | null;
}
