/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeaveRequestDto } from '../models/leave-request-dto';
export interface LeaveRequestDtoIEnumerableApiResponse {
  data?: Array<LeaveRequestDto> | null;
  message?: string | null;
  success?: boolean;
}
