/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeaveRequestDto } from '../models/leave-request-dto';
export interface LeaveRequestDtoApiResponse {
  data?: LeaveRequestDto;
  message?: string | null;
  success?: boolean;
}
