/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LeaveRequestDto {
  employeeEmail?: string | null;
  employeeFirstName?: string | null;
  employeeId?: string;
  employeeLastName?: string | null;
  endDate?: string;
  id?: string;
  reason?: string | null;
  startDate?: string;
  status?: string | null;
}
